### ISSUE TITLE
Doesn't open for / work on an all-caps font?

### ISSUE THREAD

**Issue by ryanbugden** [roboDocs/StemAnalyzer#1]
```
Traceback (most recent call last):
  File "StemAnalyzer.py", line 448, in <module>
  File "lib/fontObjects/fontPartsWrappers.pyc", line 1866, in __getitem__
KeyError: "No glyph named 'o'."
```

**Comment by connordavenport** [comment]
Ah good catch, I will fix that!

**Comment by connordavenport** [comment]
This new update should fix it, the old code was checking if the glyph was there, after keying it.
https://github.com/roboDocs/StemAnalyzer/blob/f3da8d22ae5a53fc184fbef53e71a4f3345a5bd2/StemAnalyzer.roboFontExt/lib/StemAnalyzer.py#L448-L475
